package coffeeshop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author philip
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radCOFFEE = new javax.swing.JRadioButton();
        radCAP = new javax.swing.JRadioButton();
        radTEA = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSub = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTax = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtTot = new javax.swing.JTextPane();
        btnENTER = new javax.swing.JButton();
        btnCLEAR = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setText("COFFEE SHOP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 15, -1, 34));

        radCOFFEE.setText("COFFEE - PHP 50");
        radCOFFEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCOFFEEActionPerformed(evt);
            }
        });
        getContentPane().add(radCOFFEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        radCAP.setText("CAPPUCINO- PHP 75");
        radCAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCAPActionPerformed(evt);
            }
        });
        getContentPane().add(radCAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        radTEA.setText("TEA -PHP 50");
        radTEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTEAActionPerformed(evt);
            }
        });
        getContentPane().add(radTEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel2.setText("Subtotal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel3.setText("Tax");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel4.setText("Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jScrollPane4.setViewportView(txtSub);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 76, -1));

        jScrollPane5.setViewportView(txtTax);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 76, -1));

        jScrollPane6.setViewportView(txtTot);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 76, -1));

        btnENTER.setText("ENTER");
        btnENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENTERActionPerformed(evt);
            }
        });
        getContentPane().add(btnENTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btnCLEAR.setText("CLEAR");
        btnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLEARActionPerformed(evt);
            }
        });
        getContentPane().add(btnCLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        btnEXIT.setText("EXIT");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });
        getContentPane().add(btnEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 80, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radCOFFEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCOFFEEActionPerformed
        // selects coffee option
        if(radCOFFEE.isSelected())
            radCAP.setSelected(false);
            radTEA.setSelected(false);
    }//GEN-LAST:event_radCOFFEEActionPerformed

    private void radCAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCAPActionPerformed
       //select cap
       
       if(radCAP.isSelected())
            radCOFFEE.setSelected(false);
            radTEA.setSelected(false);
       
       
    }//GEN-LAST:event_radCAPActionPerformed

    private void radTEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTEAActionPerformed
        //  Select Tea Option
        
       
    }//GEN-LAST:event_radTEAActionPerformed

    private void btnENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENTERActionPerformed
       
       
        inheritance in = new inheritance();    
        double subtotal = in.enter()+in.option();
        double tax=subtotal*0.01;
        double total = tax+subtotal;
        
        txtSub.setText(""+subtotal);
        txtTax.setText(""+tax);
        txtTot.setText(""+total);
        
    }//GEN-LAST:event_btnENTERActionPerformed

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
        // exits
        
        System.exit(0);
        
    }//GEN-LAST:event_btnEXITActionPerformed

    private void btnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLEARActionPerformed
        // Clears everything 
        
        radCOFFEE.setSelected(false);
        radCAP.setSelected(false);
        radTEA.setSelected(false);
        
        txtTot.setText("");
        txtSub.setText("");
        txtTax.setText("");
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnCLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLEAR;
    private javax.swing.JButton btnENTER;
    private javax.swing.JButton btnEXIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JRadioButton radCAP;
    public javax.swing.JRadioButton radCOFFEE;
    public javax.swing.JRadioButton radTEA;
    public javax.swing.JTextPane txtSub;
    public javax.swing.JTextPane txtTax;
    public javax.swing.JTextPane txtTot;
    // End of variables declaration//GEN-END:variables
}
